### ISSUE TITLE
test_concat does not fully running on Qemu 4.2

### ISSUE THREAD

**Issue by sakaia** [fujitsu/dnnl_aarch64#6]
test_concat does not fully running on Qemu 4.2.
The error message is follows

```
test_concat: malloc.c:4023: _int_malloc: Assertion `(unsigned long) (size) >= (unsigned long) (nb)' failed.
qemu: uncaught target signal 6 (Aborted) - core dumped
Aborted (core dumped)
```
To avoid this problem following change should be applied

```C++
diff --git a/mkl-dnn/tests/gtests/test_concat.cpp b/mkl-dnn/tests/gtests/test_concat.cpp
index b479779..66ff650 100644
--- a/mkl-dnn/tests/gtests/test_concat.cpp
+++ b/mkl-dnn/tests/gtests/test_concat.cpp
@@ -275,9 +275,9 @@ INSTANTIATE_TEST_CASE_P(TestConcat, concat_test_float, ::testing::Values(
     concat_test_params{engine::kind::cpu, 0,
     {memory::format::nChw8c, memory::format::nChw8c}, memory::format::nChw8c,
     {{2, 16, 1, 1}, {2, 16, 1, 1}}, {4, 16, 1, 1}},
-    concat_test_params{engine::kind::cpu, 0,
-    {memory::format::nchw, memory::format::nchw}, memory::format::nChw8c,
-    {{2, 16, 1, 1}, {2, 16, 1, 1}}, {4, 16, 1, 1}},
+    // concat_test_params{engine::kind::cpu, 0,
+    // {memory::format::nchw, memory::format::nchw}, memory::format::nChw8c,
+    // {{2, 16, 1, 1}, {2, 16, 1, 1}}, {4, 16, 1, 1}},
     concat_test_params{engine::kind::cpu, 0,
     {memory::format::nChw8c, memory::format::nChw8c}, memory::format::nchw,
     {{2, 16, 1, 1}, {2, 16, 1, 1}}, {4, 16, 1, 1}},
```

**Comment by sakaia** [comment]
test_concat error message and its trace

error message

```
test_concat: malloc.c:4023: _int_malloc: Assertion `(unsigned long) (size) >= (unsigned long) (nb)' failed.
```

back trace

```
#0  0x00007ffff678914d in __GI___sigprocmask (how=how@entry=2,
    set=set@entry=0x7fffffffdbe0, oset=oset@entry=0x0)
    at ../sysdeps/unix/sysv/linux/x86_64/sigprocmask.c:36
#1  0x000055555565624a in process_pending_signals (
    cpu_env=cpu_env@entry=0x555557cb4d30)
    at /work/qemu/linux-user/signal.c:987
#2  0x000055555565bcc0 in cpu_loop (env=0x555557cb4d30)
    at /work/qemu/linux-user/aarch64/cpu_loop.c:144
#3  0x00005555555eb5f4 in main (argc=<optimized out>,
    argv=0x7fffffffe518, envp=<optimized out>)
    at /work/qemu/linux-user/main.c:865
```

**Comment by kawakami-k** [comment]
I think it is same problem of #3

**Comment by kawakami-k** [comment]
I have confirmed that the test has been completed with the above modifications, so I will close this case.
